type: map
mapping: 
  "id":
    type: str
    required: true

  "name":
    type: map
    mapping:
      "cs":
        type: str
      "en":
        type: str  

  "desc":
    type: str

  "url":
    type: str

  "icon":
    type: str

  "period":
    type: str
    required: true
    enum: ["one-time", "second", "minute", "hour", "day", "week", "month", "year"]
  "currency":
    type: str
    required: true
  "attributes":
    type: seq
    required: true
    sequence:
      - type: map 
        mapping:
          "id":
            type: str
            required: true

          "type":
            type: str
            required: true
            enum: ["range", "number", "boolean", "options"]

          "options":
            type: seq
            sequence:
              -
                type: map
                mapping:
                  "id":
                    type: str
                    required: true
                  "name":
                    type: map
                    required : true
                    mapping:
                      "cs":
                        type: str
                      "en":
                        type: str  
                  "url":
                    type: str
                  "image":
                    type: str
                  "desc":
                    type: str
                  "accounting":
                    type: map
                    required: true
                    mapping:
                      "price":
                        type: number
                      "type":
                        type: str
                        enum: ["static"]  

          "name":
            type: map
            required: true
            mapping:
              "cs":
                type: str
              "en":
                type: str  

          "url":
            type: str

          "desc":
            type: str
          
          "default":
            type: number
              
          "min":
            type: number

          "max":
            type: number

          "step":
            type: number

          "unit":
            type: str

          "accounting":
            required: true
            type: map
            mapping:
              "type":
                type: str
                enum: ["linear", "formula", "static", "options"]
                required: true
              "formula":
                  type: map
                  mapping:
                    "attributes":
                      type: seq
                      required: true
                      sequence:
                        - type: str
                    "formula":
                      type: text
                      required: true
              "price":
                type: number
              
               